const baseUrl = "https://taylormade.sanchy.com.ng/public/api/";
export const loginUrl = `${baseUrl}user/login`;
export const goalUrl = `${baseUrl}configurations/goal/list`;
export const motiveUrl = `${baseUrl}configurations/motivation/list`;
export const bodyTypeUrl = `${baseUrl}configurations/bodytype/list`;
export const targetAreaURL = `${baseUrl}configurations/targetarea/list`;
export const fitnessLevelUrl = `${baseUrl}configurations/level/list`;
export const hindranceUrl = `${baseUrl}configurations/reason/list`;
export const walkoutLocationUrl = `${baseUrl}configurations/walkoutlocation/list`;
